version: '3.3'
services:
  gsf:
    tty: true
    container_name: gsf
    build:
      context: server/jvm/
      dockerfile: Dockerfile
    networks:
      qs_network:
        aliases:
          - localnode
    volumes:
      - ./server/jvm/{{appName}}-site-specific/src/main/resources/cfg/:/home/{{appName}}/run/site-specific/cfg
      - ./server/jvm/{{appName}}-script-config/src/main/resources/scripts:/home/{{appName}}/run/{{appName}}/scripts
      - ./server/jvm/{{appName}}-config/src/main/resources/cfg:/home/{{appName}}/run/{{appName}}/cfg
    ports:
      - '9064:9064'
      - '1337:22'
      - '5432:5432'
      - '4569:4569'
  nginx:
    ports:
      - '80:80'
      - '443:443'
    container_name: nginx
    build:
      context: server/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./client/dist:/usr/share/nginx/html/
    networks:
      - qs_network
networks:
  qs_network:
    driver: bridge
